### ISSUE TITLE
Groups and Users 

### ISSUE THREAD

**Issue by msuzoagu** [msuzoagu/cloudformation_template_for_terraform_operational_resources#5]
# Thinking through some improvements

Small team thus currently handling password, Mfa, and console access manually. 

Would like to:
1. Auto generate user first password && force user to change password on first log in
    - do I need secret manager for this?
      -  possibly: 
          ```
            Resources:            
            Passwrd:
              Type: 'AWS::SecretsManager::Secret'
              Condition: ConsoleAllowed
              Properties:
                Name: !Sub ${NameParam}-Password
                GenerateSecretString:
                  SecretStringTemplate:
                        !Join
                          - ''
                          - - '{"username": "'
                            - !Ref NameParam
                            - '"}'
                  GenerateStringKey: password
                  PasswordLength: 20

            User:
              Type: AWS::IAM::User
              Properties:
                UserName: !Ref NameParam
                ManagedPolicyArns:
                  !If
                    - AssignManagedPolicy
                    - 
                      - !Ref ManagedPolicyArnParam
                    - !Ref AWS::NoValue
                LoginProfile:
                  Fn::If: 
                    - ConsoleAllowed
                    - 
                      Password: !Sub "{{resolve:secretsmanager:${Passwrd}:SecretString:password}}"
                      PasswordResetRequired: true
                    - Ref: AWS::NoValue
          ```

 

2. Improve `CommonGroupPermissionPolicy` by: 
    - [ ] add policy granting console access to users  
    - [ ] add policy [allowing users to change their own passwords](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_aws_my-sec-creds-self-manage-password-only.html)
    - [ ] add policy that forces users to change password on first sign in 
    - [ ] add policy that requires [MFA for all users](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-virtualmfadevice.html)
    - [ ] add policy enforcing regular access keys rotation
